### PR TITLE
Allow cloned repos to work correctly with travis-cl.

### PR DESCRIPTION
**Pull request by tomrake**
Fix for #356 use the ${TRAVIS_REP_SLUG} to refer to your own repo from travis. This is **the right thing** in a repo that could be cloned.

### CODE REVIEW

**Comment by snmsts** [comment]
Seems good only on travis environment.
Would you consider making it work when ``TRAVIS_REP_SLUG`` aren't set?

**Comment by snmsts** [comment]
``install-for-ci.sh`` are mainly used to setup roswell envrionment to use roswell for test.

**Comment by snmsts** [comment]
why don't you set ``ROSWELL_REPO`` on your travis envrionment?

**Comment by tomrake** [comment]
Thank you for your comments. 

After consideration of all your comments, I believe setting ROSWELL_REPO is best done in .travis.yml global environment by using TRAVIS_REPO_SLUG.

I will push changes to this pull request when I verify they work on my clone.

**Comment by tomrake** [comment]
Thank you.
The Pull Request has been updated to _0c8cc6d_  in response and consideration of your comments, please review current version of this PR.
1) This is a travis only issue and _install-for-ci.sh_ is not changed.
2) Only Travis configuration _.travis.yml_ is changed.

Why do I want this? I am working on Windows-mingw64 builds of Roswell.  I have found one automake related problem in my debugging. I want to review travis and appveyor results to check for errors.

**Comment by snmsts** [comment]
Thank you and sorry for careless review.

**Pull request merged**
