### PR TITLE
Fix usage of Roswell under the Qlot environment

### PR DESCRIPTION
**Pull request by svetlyak40wt**
Before this fix command like:

    qlot exec ros install 40ants/gh-pages

resulted in error. But I wanted to use it, to install
scripts into a local `.qlot` environment.

### Tested on

```
$ ros version
roswell 20.06.14.107
build with Apple clang version 12.0.0 (clang-1200.0.32.28)
libcurl=7.64.1
ASDF=3.3.4
Quicklisp=2020-01-04
Dist=2020-07-15
lispdir='/Users/art/.local/etc/roswell/'
homedir='/Users/art/.roswell/'

$ ros config
sigsegv.version=2.11
externals.clasp.version=6.0.1
allegro.version=10.1express
abcl-bin.version=1.6.0
asdf.version=3.3.4
sly.version=git
ccl-bin.version=1.12
sbcl.version=2.1.0
emacs.type=sly
slime.version=2019.03.07
setup.time=3819480448
sbcl-bin.version=2.0.11
default.lisp=sbcl-bin
```

### How to reproduce

To reproduce, checkout "release" branch of the Roswell and run this command to reinstall Roswell from sources (you have to follow [this instruction first](https://github.com/roswell/roswell/wiki/Installation#building-from-source):

```
make clean && make && make install
```

Then create a temp directory and do following:

```
mkdir -p /tmp/test-qlot
cd /tmp/test-qlot

touch qlfile
qlot install

qlot exec ros install 40ants/defmain
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                  {1001580563}>:
  The value
    NIL
  is not of type
    (OR (VECTOR CHARACTER) BASE-STRING PATHNAME SYNONYM-STREAM FILE-STREAM)
  when binding SB-IMPL::DEFAULTS

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001580563}>
0: (MERGE-PATHNAMES "../" NIL #<unavailable argument>) [external]
1: (CHECKOUTDIR)
2: (CLONE-GITHUB "40ants" "defmain" :ALIAS NIL :BRANCH NIL :FORCE-GIT NIL :GIT T :FORCE-UPDATE NIL :PATH "local-projects" :HOME NIL)
3: (INSTALL NIL)
4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
6: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
7: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
8: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
9: ((FLET SB-FASL::THUNK :IN LOAD))
10: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {18E55EB}> #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}>)
11: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> NIL)
12: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
13: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /Users/art/.local/etc/roswell/install.ros" {10043A0A33}>)
14: (ROSWELL:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain")
15: (ROSWELL:RUN ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))
16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))) #<NULL-LEXENV>)
17: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))))
18: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/Users/art/.local/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:asdf)\")(:eval\"(ros:quicklisp)\")(:script \"/Users/art/.local/etc/roswell/install.ros\"\"40ants/defmain\")(:quit ())))")))
19: (SB-IMPL::TOPLEVEL-INIT)
20: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
22: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quittingqlot exec ros install 40ants/defmain
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                  {1001580563}>:
  The value
    NIL
  is not of type
    (OR (VECTOR CHARACTER) BASE-STRING PATHNAME SYNONYM-STREAM FILE-STREAM)
  when binding SB-IMPL::DEFAULTS

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001580563}>
0: (MERGE-PATHNAMES "../" NIL #<unavailable argument>) [external]
1: (CHECKOUTDIR)
2: (CLONE-GITHUB "40ants" "defmain" :ALIAS NIL :BRANCH NIL :FORCE-GIT NIL :GIT T :FORCE-UPDATE NIL :PATH "local-projects" :HOME NIL)
3: (INSTALL NIL)
4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (APPLY (QUOTE MAIN) ROSWELL:*ARGV*) #<NULL-LEXENV>)
5: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) #<NULL-LEXENV>)
6: (SB-EXT:EVAL-TLF (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL NIL)
7: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ROSWELL:QUIT (APPLY (QUOTE MAIN) ROSWELL:*ARGV*)) NIL)
8: (SB-INT:LOAD-AS-SOURCE #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
9: ((FLET SB-FASL::THUNK :IN LOAD))
10: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {18E55EB}> #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}>)
11: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> NIL)
12: (LOAD #<CONCATENATED-STREAM :STREAMS NIL {10043A8D33}> :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
13: ((FLET ROSWELL::BODY :IN ROSWELL:SCRIPT) #<SB-SYS:FD-STREAM for "file /Users/art/.local/etc/roswell/install.ros" {10043A0A33}>)
14: (ROSWELL:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain")
15: (ROSWELL:RUN ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))
16: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ROSWELL:RUN (QUOTE ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))) #<NULL-LEXENV>)
17: (EVAL (ROSWELL:RUN (QUOTE ((:EVAL "(ros:asdf)") (:EVAL "(ros:quicklisp)") (:SCRIPT "/Users/art/.local/etc/roswell/install.ros" "40ants/defmain") (:QUIT NIL)))))
18: (SB-IMPL::PROCESS-EVAL/LOAD-OPTIONS ((:EVAL . "(progn #-ros.init(cl:load \"/Users/art/.local/etc/roswell/init.lisp\"))") (:EVAL . "(ros:run '((:eval\"(ros:asdf)\")(:eval\"(ros:quicklisp)\")(:script \"/Users/art/.local/etc/roswell/install.ros\"\"40ants/defmain\")(:quit ())))")))
19: (SB-IMPL::TOPLEVEL-INIT)
20: ((FLET SB-UNIX::BODY :IN SB-IMPL::START-LISP))
21: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-IMPL::START-LISP))
22: (SB-IMPL::START-LISP)

unhandled condition in --disable-debugger mode, quitting
```

### A warning

This fix works with a single problem I wasn't able to
resolve. After the fresh Roswell install, you have to
run some command like `ros config` without Qlot, to let
Roswell dump an image. Otherwise, you'll get this error
when running `qlot exec ros install some-system`:

    no dispatch function defined for #\!

#### How to reproduce this dispatch problem

Run this command to reinstall Roswell from sources (you have to follow [this instruction first](https://github.com/roswell/roswell/wiki/Installation#building-from-source):

```
make clean && make && make install
```

Then create a temp directory and do following:

```
mkdir -p /tmp/test-qlot
cd /tmp/test-qlot

touch qlfile
qlot install

qlot exec ros config
Making core for Roswell...
building dump:/Users/art/.roswell/env/roswell/impls/x86-64/darwin/sbcl-bin/2.0.2/dump/roswell.core
Unhandled SB-C::INPUT-ERROR-IN-LOAD in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                 {1000518083}>:
  READ error during LOAD:

    no dispatch function defined for #\!

      Line: 1, Column: 2, File-Position: 1

      Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /Users/art/.local/etc/roswell/balus.ros" {10046038C3}>

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1000518083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SB-C::INPUT-ERROR-IN-LOAD {10046055D3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SB-C::INPUT-ERROR-IN-LOAD {10046055D3}>)
2: (INVOKE-DEBUGGER #<SB-C::INPUT-ERROR-IN-LOAD {10046055D3}>)
3: (ERROR #<SB-C::INPUT-ERROR-IN-LOAD {10046055D3}>)
4: (SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-ERROR "no dispatch function defined for ~S" {1004605583}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /Users/art/.local/etc/roswell/balus.ros" {10046038C3}>)
5: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100460552B}> #<SB-C::SOURCE-INFO {10046054F3}> SB-C::INPUT-ERROR-IN-LOAD)
6: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file /Users/art/.local/etc/roswell/balus.ros" {10046038C3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
7: ((FLET SB-FASL::THUNK :IN LOAD))
8: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {F0B56CB}> #<SB-INT:FORM-TRACKING-STREAM for "file /Users/art/.local/etc/roswell/balus.ros" {10046038C3}>)
```

### CODE REVIEW

**Comment by snmsts** [comment]
looks good for me.

**Comment by svetlyak40wt** [comment]
Thank you!

**Comment by svetlyak40wt** [comment]
@snmsts how to create a new Roswell release in the `rellease` branch?

Without release URL https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh still installs a version without this fix.

**Comment by snmsts** [comment]
need to fix ci. I notice this patch breaks everything on travis.

**Comment by snmsts** [comment]
do you use roswell in daily use?

**Comment by snmsts** [comment]
sorry my bad...

**Comment by svetlyak40wt** [comment]
I see you've already fixed the problem. But don't understand how these fixes are related to the `run-prove: command not found` error.

Could you explain, please?

**Comment by snmsts** [comment]
Expected installation directory for 'run-prove' is under "~/.roswell/bin/" but it is installed under somewhere else.
I guess it's faster to share where to read than by my English.

https://github.com/roswell/roswell/blob/a8fd8a3c33078d6f06e6cda9d099dcba6fbefcb7/lisp/util.lisp#L222-L228
https://github.com/roswell/roswell/blob/a8fd8a3c33078d6f06e6cda9d099dcba6fbefcb7/lisp/util-install-quicklisp.lisp#L131

**Comment by svetlyak40wt** [comment]
Oh, that is interesting. I've experienced this problem today when used my Roswell fork (without your fixes).

But I wasn't able to figure out why installation dir has changed from `~/.roswell/bin` to `~/.roswell/lisp/quicklisp/bin`. I decided it is probably because I'm hacked install path in my CI script:

https://github.com/40ants/log4cl-extras/blob/master/.github/workflows/tests.yml#L59-L60

**Comment by svetlyak40wt** [comment]
I've updated my fork and changed path back to `~/.roswell/bin` and everything work now!

**Comment by snmsts** [comment]
so. everything fine for you?

**Comment by svetlyak40wt** [comment]
Yes.

**Pull request merged**
