### PR TITLE
Use compression when building executable with SBCL.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
With this one line patch, I've got 16M binary instead of 83.

### CODE REVIEW

**Comment by snmsts** [comment]
Thank you for your effort and I agree with your comment.
I can't take this patch directly cause default windows binary doesn't have core compression facility and I don't know how to know runtime have it or not from lisp.

There must be a way...

**Comment by svetlyak40wt** [comment]
SANO, thank you for a quick reply.

By the way, I see, that UIOP does not make difference for windows or other systems in the `dump-image`: https://github.com/fare/asdf/blob/master/uiop/image.lisp#L406

But they check `#+(and sbcl os-windows)` features to include or not another option `:application-type`.

Are you sure that Windows does not support compression? If yes, then I'll figure out how to do it and will fix the patch.

**Comment by svetlyak40wt** [comment]
Hey, I found how to check it. Here is how `trivial-build` works:

https://github.com/ceramic/trivial-build/blob/master/src/trivial-build.lisp#L21

It just checks a feature: `#+sb-core-compression :compression #+sb-core-compression t`.

**Comment by svetlyak40wt** [comment]
Updated patch.

**Comment by snmsts** [comment]
LGTM.

**Pull request merged**
