### PR TITLE
Fix completion install

### PR DESCRIPTION
**Pull request by guicho271828**
This pull request enables the automatic conditional installation of the bash completion scripts.

Installation can be explicitly enabled/disabled by **--with/without-bash/zsh-completion**.
When neither are specified, scripts are automatically installed when `pkg-config` detects the presence of `bash-completion`.

Completion scripts are installed into a correct destination suggested by `pkg-config`, rather than the current destination (`$roslisp_DATA`, which is `/usr/local/share/common-lisp/source/roswell` on linux, which is not known to `bash-completion`).

The destination can be optionally configured by **--with-bash/zsh-completion=[DIR]**.

### CODE REVIEW

**Comment by snmsts** [comment]
Is it ready for merge?

**Comment by guicho271828** [comment]
there seems to be an M4-related errors.

**Comment by guicho271828** [comment]
it seems ok, but appveyor shows weird logs. it looks like the installation hits a maximum number of processes. could it be merged?

**Comment by snmsts** [comment]
for windows,I'll focus later.

**Comment by guicho271828** [comment]
thanks!

**Pull request merged**
