### PR TITLE
Completion (Again, don't merge it yet!)

### PR DESCRIPTION
**Pull request by guicho271828**
In addition to the completion feature, I added a common specification which can facilitate the completion mechanism. See the new HACKING.md . Not all subcommands of roswell satisfy this specification currently. This PR should be merged only when this is fixed.

+ [X] ros install
+ [x] ros dump
+ [x] ros config
+ [x] ros help
+ [x] ros use
+ [x] ros list
+ [x] ros delete

### CODE REVIEW

**Comment by snmsts** [comment]
why do you make it pull request now then? :)

**Comment by guicho271828** [comment]
I need a place for discussion and review

**Comment by snmsts** [comment]
ok.

**Comment by guicho271828** [comment]
now its ready!

**Comment by eudoxia0** [comment]
:clap: :confetti_ball:

**Pull request merged**
