### PR TITLE
Clarified usage of a system implementation

### PR DESCRIPTION
**Pull request by PF4Public**
As suggested in #416

### CODE REVIEW

**Comment by snmsts** [comment]
"which is only used internally" seems not right for me. It's also default implementation for "ros run" as well.

**Comment by PF4Public** [comment]
What would be a better wording?

**Comment by snmsts** [comment]
how about just remove it?

**Comment by PF4Public** [comment]
> how about just remove it?

How does one use system implementation? That is absolutely non-obvious from the current README.

Maybe something like this: `which will be only used internally if using system implementation later on with ros use sbcl/system`?

**Comment by snmsts** [comment]
I don't mean remove all of your sentence.

> By default roswell downloads the default newest lisp implementation (sbcl-bin). To use system implementation from the start run `ros lisp=sbcl-bin/system setup` before anything else.

how about it?

**Comment by PF4Public** [comment]
> I don't mean remove all of your sentence.
Sorry, I misunderstood you from the beginning.

> how about it?
Come to think of it, it's indeed better. I can do a force-push later today.

**Comment by PF4Public** [comment]
> I can do a force-push later today.

Done

**Comment by snmsts** [comment]
Thank you. I felt this function is half baked status and I have hesitance to share about it.

**Comment by PF4Public** [comment]
But it worked for me flawlessly! :)

**Comment by PF4Public** [comment]
I've just recreated .roswell folder and tried `ros lisp=sbcl-bin/system setup`. It does not show any output about downloading sbclbin, but in fact does download a sbcl-bin and use it nonetheless. After I've removed the binary ros exits with the following error: `sbcl-bin/2.0.11 does not exist.stop.` Seems, that this feature is indeed unfinished :(

**Pull request merged**
