### PR TITLE
bash completion

### PR DESCRIPTION
**Pull request by guicho271828**
don't merge it yet, its a stub!

### CODE REVIEW

**Comment by snmsts** [comment]
Thanks!

**Comment by guicho271828** [comment]
eww, it's not reaching the quality to be merged...

**Comment by guicho271828** [comment]
tasks:
+ [ ] let `make install` copy /etc/bash_completion.d
+ [ ] check if it actually works (its not tested yet!)
+ [ ] add the actual contents

**Comment by snmsts** [comment]
sorry. I missed.

**Pull request merged**
